version: 2.1
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:10
    parallelism: 4
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm
          command: npm install --production
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: test-js
          command: npm run test-js
      - run:
          name: test-css
          command: npm run test-css
